version: 1
default: prprprpr.md
templates:
  - name: PR template test 1
    description: PR template test 1
    filename: prprprpr.md
  - name: PR template test 2
    description: PR template test 2
    filename: prrrrrr.yml