---
name: Default PR Template
description: A default template for pull requests.
body:
  - type: markdown
    attributes:
      value: |
        # Pull Request Template

        ## Description
        Please provide a brief description of the changes made in this PR.

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: List any related issues or pull requests.
      placeholder: Fixes #123
