name: dispatch

on:
  workflow_dispatch:
    inputs:
      build-plugin:
        description: 'Build plugin'
        required: false
        default: true
        type: boolean
      build-Docusaurus:
        description: 'Build docusaurus'
        required: false
        default: true
        type: boolean
      additional-functions:
        description: "Additional functions"
        required: false
        default: 'Not used'
        type: choice
        options:
        - Not used
        - PR Approve
        - Deploy gitHub pages
      PR_ID:
        description: 'PR Approve ID'
        required: false
      Release_version:
        description: 'Release version'
        required: false

env:
  TZ: Asia/Shanghai

jobs:
  initialize:
    runs-on: ubuntu-slim
    steps:
      - run: echo 1145141919810 && sleep 10
      - parallel:
        - name: Build frontend
          run: echo 114514 && sleep 5
        - name: Build backend
          run: echo 1919810 && sleep 5
        - name: Build docs
          run: echo axdvfbgvr && sleep 5

      - name: Build frontend
        id: step-1
        run: echo iiiiiiiiiiii && sleep 5
        background: true

      - name: Build backend
        id: step-2
        run: echo errrrrrrrrrrrr && sleep 5
        background: true

      - name: Run linter while builds run
        run: echo xxxxxxxxxxx && sleep 5

      - name: Wait for both builds to finish
        wait: [step-1, step-2]

      - name: Run tests
        run: echo 11111111111 && sleep 5

      - name: Run tests
        run: echo 11dddddd11111 && sleep 5
