name: dispatch

on:
  workflow_dispatch:
    inputs:
      build-plugin:
        description: 'Build plugin'
        required: false
        default: true
        type: boolean
      build-Docusaurus:
        description: 'Build docusaurus'
        required: false
        default: true
        type: boolean
      additional-functions:
        description: "Additional functions"
        required: false
        default: 'Not used'
        type: choice
        options:
        - Not used
        - PR Approve
        - Deploy gitHub pages
      PR_ID:
        description: 'PR Approve ID'
        required: false
      Release_version:
        description: 'Release version'
        required: false

env:
  TZ: Asia/Shanghai

jobs:
  initialize:
    runs-on: ubuntu-slim
    steps:
      - run: echo QWQ--0000 && sleep 10

      - parallel:
        - name: a0001
          run: echo QWQ--0001 && sleep 5
        - name: a0002
          run: eecho QWQ >> 0002 && sleep 5
        - name: a0003
          run: echo QWQ---0003 && sleep 5

      - name: a0004
        id: step-1
        run: echo QWQ---0004 && sleep 5
        background: true

      - name: a0005
        id: step-2
        run: echo QWQ---0005 && sleep 5
        background: true

      - name: a0006
        run: echo QWQ---0006 && sleep 15

      - name: Wait for both builds to finish
        wait-all:

      - name: a0007
        run: echo QWQ---0007 && sleep 5

      - name: a0008
        run: echo QWQ---0008 && sleep 5
