name: dispatch2
on:
  workflow_dispatch:
    inputs:
      build-plugin:
        description: 'Build plugin'
        required: false
        default: true
        type: boolean
      build-Docusaurus:
        description: 'Build docusaurus'
        required: false
        default: true
        type: boolean
      deploy-gitHub-pages:
        description: 'Deploy gitHub pages'
        required: false
        default: false
        type: boolean
      PR_Approve:
        description: 'PR Approve'
        required: false
        default: false
        type: boolean
      PR_ID:
        description: 'PR Approve ID'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      artifact_name: ${{ steps.get_info.outputs.repository_name }}-Dispatch2-Build_${{ github.run_number}}
    steps:
    - name: 获取输入参数
      run: |
        echo Build plugin : ${{ inputs.build-plugin }}
        echo Build docusaurus : ${{ inputs.build-Docusaurus }}
        echo Deploy gitHub pages : ${{ inputs.deploy-gitHub-pages }}
        echo PR Approve : ${{ inputs.PR_Approve }}
        echo PR Approve ID : ${{ inputs.PR_ID }}
    - name: 获取信息
      id: get_info
      run: echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
    - name: 设置信息
      id: set_info
      run: |
        if [[ "${{ inputs.PR_Approve }}" == "true" && "${{ inputs.deploy-gitHub-pages }}" == "false" ]]; then
          echo "run_PR_Approve=run" >> $GITHUB_OUTPUT
        else
          echo "run_PR_Approve=no_run" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ inputs.deploy-gitHub-pages }}" == "true" && "${{ inputs.PR_Approve }}" == "false" ]]; then
          echo "run_Deploy_gitHub_pages=run" >> $GITHUB_OUTPUT
        else
          echo "run_Deploy_gitHub_pages=no_run" >> $GITHUB_OUTPUT
        fi
    - run: echo 114514
      if: (${{ !inputs.deploy-gitHub-pages }} == 'false') && (${{ inputs.PR_Approve }} == 'true')
    - run: echo 1919810
      if: (${{ inputs.deploy-gitHub-pages }} == 'true') && (${{ inputs.PR_Approve }} == 'true')
    - run: echo 1145141919810
      if: (${{ inputs.PR_Approve }} == 'true')
    - run: echo hello
      if: (${{ inputs.deploy-gitHub-pages }} == 'false')
    - run: echo world
      if: steps.set_info.outputs.run_PR_Approve == 'run'
    - run: echo hello world
      if: steps.set_info.outputs.run_Deploy_gitHub_pages == 'run'