name: sd
on:
  workflow_dispatch:
    inputs:
      run_type:
        description: '运行方式'
        required: true
        default: '构建快照'
        type: choice
        options:
        - 构建快照
        - 批准PR
        - 发布预览版
      PR_ID:
        description: 需要批准的PR ID
        required: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: 获取信息
        run: |
          echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
          echo 本次运行方式: ${{ inputs.run_type }}
      - name: 构建快照 or 发布预览版
        if: inputs.run_type == '构建快照' || inputs.run_type == '发布预览版'
        uses: actions/checkout@v4.1.1
      - name: 批准PR
        if: inputs.run_type == '批准PR'
        uses: actions/checkout@v4.1.1
        with:
          ref: remotes/pull/${{ inputs.PR_ID }}/merge
