name: sd
on:
  workflow_dispatch:
    inputs:
      run_type:
        description: '运行方式'
        required: true
        default: '构建快照'
        type: choice
        options:
        - 构建快照
        - 批准PR
        - 发布预览版
      PR_ID:
        description: 需要批准的PR ID
        required: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: 获取信息
        id: get_info
        run: |
          echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
          echo 本次运行方式: ${{ inputs.run_type }}
          if [ "$inputs.run_type" == "构建快照" ]; then
            echo "run_type_en=SNAPSHOT" >> $GITHUB_OUTPUT
          elif [ "$inputs.run_type" == "批准PR" ]; then
            echo "run_type_en=PR Approve" >> $GITHUB_OUTPUT
          else
            echo "run_type_en=Preview" >> $GITHUB_OUTPUT
          fi
      - name: 拉取代码
        uses: actions/checkout@v3
      # 必须先执行一次checkout才能执行这个
      - name: 拉取代码(批准PR专用)
        if: inputs.run_type == '批准PR'
        run: |
          ls -la
          rm -rf ./*
          ls -la
          gh pr checkout ${{ inputs.PR_ID }}
          ls -la
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}