name: 测试
on:
  push:
jobs:
  # TEST1:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     repo: ${{ steps.get_info.outputs.repo_name }}
  #     ref: ${{ steps.get_info.outputs.secondword }}
  #   steps:
  #   - name: 获取信息
  #     id: get_inf
  #     run: |
  #       echo "repo_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
  #       echo "ref=${{ GITHUB.REF }}" >> $GITHUB_OUTPUT
  # TEST2:
  #   runs-on: ubuntu-latest
  #   needs: [TEST1] 
  #   steps:
  #   - name: echo
  #     run: |-
  #       echo 仓库 ${{ needs.TEST1.outputs.repo_name }}
  #       echo 所有者 ${{ github.repository_owner }}
  #       echo ${{ github.repository_owner }}/${{ needs.TEST1.outputs.repo_name }}
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - name: Build
        id: build_step
        run: echo "build_id=$RANDOM" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying build ${{ needs.build.outputs.build_id }}"
  debug:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "Failed to build and deploy"