name: test 4

on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl https://api.github.com/repos/stevei5mc/AutoRestart/releases
    - run: gh api repos/stevei5mc/AutoRestart/releases
    - run: curl https://api.github.com/repos/stevei5mc/AutoRestart/releases/tags/1.0.0-beta5
    - run: gh api repos/stevei5mc/AutoRestart/releases/tags/1.0.0-beta5
    - run: curl https://api.github.com/repos/stevei5mc/AutoRestart/releases/tags/1.0.0-beta6
    - run: gh api repos/stevei5mc/AutoRestart/releases/tags/1.0.0-beta6