name: 测试
on:
  push:
jobs:
  TEST1:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.get_info.outputs.repo_name }}
      ref: ${{ steps.get_info.outputs.secondword }}
    steps:
    - name: 获取信息
      id: get_inf
      run: |
        echo "repo_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
        echo "ref=${{ GITHUB.REF }}" >> $GITHUB_OUTPUT
  TEST2:
    runs-on: ubuntu-latest
    needs: [TEST1] 
    steps:
    - name: echo
      run: |-
        echo 仓库 ${{ jobs.TEST1.outputs.repo }}
        echo 所有者 ${{ github.repository_owner }}
        echo ${{ github.repository_owner }}/${{ jobs.TEST1.outputs.repo }}