name: workflow test
on:
  push:
  workflow_dispatch:
  pull_request:

env:
  token1: ${{ github.token }}
  token2: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ github.token }}

jobs:
  TEST-Linux:
    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: ubuntu-latest, type: fastfetch-linux-amd64.deb}
        - {os: ubuntu-24.04-arm, type: fastfetch-linux-aarch64.deb}
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
    - run: ip addr show
    - run: hostname


  TEST-Windows:
    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: windows-latest, type: fastfetch-windows-amd64.zip}
        - {os: windows-11-arm, type: fastfetch-windows-aarch64.zip}
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
    - run: ipconfig
      shell: cmd
    - run: hostname
      shell: cmd