name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4
      with:
        submodules: true
        repository: 'stevei5mc/ServerHelper'
    - name: 安装java17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: 构建
      run: |
        mvn package
        mkdir staging
        cd ./Nukkit
        mkdir staging
        cp target/*.jar staging
        cd staging
        bash ../../.github/workflows/get_build_files_hash.sh "Nukkit"
        cd ../../WaterdogPE
        mkdir staging
        cp target/*.jar staging
        cd staging
        bash ../../.github/workflows/get_build_files_hash.sh "WaterdogPE"
        cd ../../
        cp ./Nukkit/staging/*.* ./staging
        cp ./WaterdogPE/staging/*.* ./staging
        bash .github/workflows/organize_resources.sh "${{ needs.initialize.outputs.repo_name }}"
