name: workflow test
on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      changed_fies: ${{ steps.changed-fies.outputs.all_changed_and_modified_files }}
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      ref: ${{ steps.get_info.outputs.ref }}
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "repo_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
        echo "ref=${{ GITHUB.REF }}" >> $GITHUB_OUTPUT
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
    # - name: Cache test
    #   uses: actions/cache@v4.0.2
    #   with:
    #     path: |
    #       ./CacheTest
    #     key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
    - name: file
      run: |
        pwd
        mkdir CacheTest
        ls -la
        cd ./CacheTest
        touch 1.txt
        touch 2.txt
        touch 3.txt
        touch 4.txt
        touch 5.txt
        cd ../
    - name: 检查改动文件
      id: changed-fies
      uses: tj-actions/changed-files@v45.0.3
    - name: 输出改动文件
      run: echo ${{ steps.changed-fies.outputs.all_changed_and_modified_files }}

  build:
    needs: initialize
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4.1.6 
      # - name: Cache test
      #   uses: actions/cache@v4.0.2
      #   with:
      #     path: |
      #       ./CacheTest
      #     key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
      - name: Build
        id: build_step
        run: echo "build_id=$RANDOM" >> $GITHUB_OUTPUT
      - name: echo
        run: |-
          echo 仓库 ${{ needs.initialize.outputs.repo_name }}
          echo 所有者 ${{ github.repository_owner }}
          echo ${{ github.repository_owner }}/${{ needs.initialize.outputs.repo_name }}

  TEST:
    strategy:
      matrix:
        include:
          - name: "TEST 1"
            path: "test1"
          - name: "TEST 2"
            path: "test2"
          - name: "TEST 3"
            path: "test3"
    runs-on: ubuntu-latest
    needs: build
    name: ${{ matrix.name }}
    if: contains(needs.initialize.outputs.changed_fies, 'matrix.path/') || contains(needs.initialize.outputs.changed_fies, 'test.txt')
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
    # - name: Cache test
    #   uses: actions/cache@v4.0.2
    #   with:
    #     path: |
    #       ./CacheTest
    #     key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
    - name: test
      run: |-
       pwd
       mkdir test
       touch Hello.txt
       touch World.txt
       ls -la
       cp ./*.txt test
       mkdir test/HelloWorld
       touch test/HelloWorld/helloWorld.txt
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ matrix.name }}
        path: test

  deploy:
    needs: TEST
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4.1.6 
      - run: echo "Deploying build ${{ needs.build.outputs.build_id }}"
      # - name: Cache test
      #   uses: actions/cache@v4.0.2
      #   with:
      #     path: |
      #       ./CacheTest
      #     key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
      - name: test
        run: |-
          pwd
          mkdir test
          touch Hello.txt
          touch World.txt
          ls -la

  debug:
    needs: 
      - deploy
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "Failed to build and deploy"