name: test3
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: T1
      uses: stevei5mc/Get-PR-info-action@dev
      with:
        repoName: Predidit/Kazumi
        prId: '753'
    - name: T2
      uses: stevei5mc/Get-PR-info-action@dev
      with:
        repoName: Predidit/Kazumi
        prId: '582'