name: test3
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: T1
      uses: stevei5mc/Get-PR-info-action@dev
      with:
        repoName: Predidit/Kazumi
        prId: '753'
    - name: T2
      uses: stevei5mc/Get-PR-info-action@dev
      with:
        repoName: Predidit/Kazumi
        prId: '582'
    - name: Get Latest Release
      uses: pozetroninc/github-action-get-latest-release@v0.8.0
      id: latest_pre_release
      with:
        repository: hiddify/hiddify-app
        excludes: release
    - name: Print latest pre-release tag
      run: echo "Latest pre-release tag is ${{ steps.latest_pre_release.outputs.release }}"