name: test2
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4
    - name: 构建
      run: |
        mkdir test
        ls -la
        cp .github/message_template/test.txt ./test
        cat << EOF >> ./test/url.txt
        github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        EOF
        cd test
        cat *.txt | tee 1.txt
        cat test.txt url.txt > 2.txt
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: test
        path: test
    - name: Add PR Comment
      uses: mshick/add-pr-comment@v2.8.2
      with:
        issue: '2'
        message-path: ./test/1.txt