name: 测试
on:
  push:
  workflow_dispatch:
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      ref: ${{ steps.get_info.outputs.ref }}
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "repo_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
        echo "ref=${{ GITHUB.REF }}" >> $GITHUB_OUTPUT
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
    - name: Cache test
      uses: actions/cache@v4.0.2
      with:
        path: |
          ./CacheTest
        key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
    - name: file
      run: |
        pwd
        mkdir CacheTest
        ls -la
        cd ./CacheTest
        touch 1.txt
        touch 2.txt
        touch 3.txt
        touch 4.txt
        touch 5.txt
        cd ../
  TEST1:
    runs-on: ubuntu-latest
    needs: initialize
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
    - name: Cache test
      uses: actions/cache@v4.0.2
      with:
        path: |
          ./CacheTest
        key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
    - name: echo
      run: |-
        echo 仓库 ${{ needs.initialize.outputs.repo_name }}
        echo 所有者 ${{ github.repository_owner }}
        echo ${{ github.repository_owner }}/${{ needs.initialize.outputs.repo_name }}
    - name: test
      run: |-
       pwd
       mkdir test
       touch Hello.txt
       touch World.txt
       ls -la
       ls -la CacheTest
    - name: test2
      run: |-
       pwd
       cp ./*.txt test
       mkdir test/HelloWorld
       touch test/HelloWorld/helloWorld.txt
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: test-TEST1
        path: test
    - name: test
      run: |-
       pwd
       ls -la test
  build:
    needs: initialize
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4.1.6 
      - name: Cache test
        uses: actions/cache@v4.0.2
        with:
          path: |
            ./CacheTest
          key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
      - name: Build
        id: build_step
        run: echo "build_id=$RANDOM" >> $GITHUB_OUTPUT
  TEST2:
    needs: initialize
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4.1.6 
    - name: Cache test
      uses: actions/cache@v4.0.2
      with:
        path: |
          ./CacheTest
        key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
    - name: zip files
      run: |-
        mkdir test
        touch Hello.txt
        touch World.txt
        zip HelloWorld.zip ./*.txt
        cp ./HelloWorld.zip test
        ls -la CacheTest
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: test-TEST2
        path: test
  deploy:
    needs: 
    - TEST1
    - build
    - TEST2
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4.1.6 
      - run: echo "Deploying build ${{ needs.build.outputs.build_id }}"
      - name: Cache test
        uses: actions/cache@v4.0.2
        with:
          path: |
            ./CacheTest
          key: ${{ runner.os }}-${{ hashFiles('**/test.txt') }}
  # debug:
  #   needs: 
  #     - deploy
  #     - TEST2
  #   runs-on: ubuntu-latest
  #   if: ${{ failure() }}
  #   steps:
  #     - run: echo "Failed to build and deploy"
