name: test 4

on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir test
    - name: Get status
      id: get_info
      run: |
        STATUS_CODE=$(curl -o ./test/1.txt -s -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releasestags/1.0.0-beta1)
        echo "v1=$STATUS_CODE" >> $GITHUB_OUTPUT
        STATUS_CODE=$(curl -o ./test/2.txt -s -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releasestags/1.0.0-beta2)
        echo "v2=$STATUS_CODE" >> $GITHUB_OUTPUT
        STATUS_CODE=$(curl -o ./test/3.txt -s -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releasestags/1.0.0-beta3)
        echo "v3=$STATUS_CODE" >> $GITHUB_OUTPUT
        STATUS_CODE=$(curl -o ./test/4.txt -s -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releasestags/1.0.0-beta4)
        echo "v4=$STATUS_CODE" >> $GITHUB_OUTPUT
        STATUS_CODE=$(curl -o ./test/5.txt -s -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releasestags/1.0.0-beta5)
        echo "v5=$STATUS_CODE" >> $GITHUB_OUTPUT
        STATUS_CODE=$(curl -o ./test/6.txt -s -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releasestags/1.0.0-beta6)
        echo "v6=$STATUS_CODE" >> $GITHUB_OUTPUT
    - name: Output get info
      run: |
        echo v1 ${{ steps.get_info.outputs.v1 }}
        echo v2 ${{ steps.get_info.outputs.v2 }}
        echo v3 ${{ steps.get_info.outputs.v3 }}
        sleep 10
        echo v4 ${{ steps.get_info.outputs.v4 }}
        echo v5 ${{ steps.get_info.outputs.v5 }}
        echo v6 ${{ steps.get_info.outputs.v6 }}
    - name: echo
      run: |
        echo release: '${{ steps.get_release.outputs.data }}'
        echo release: '${{ steps.get_release2.outputs.data }}'